development:
  sessions:
    default:
      database: ucandidate_api_development
      hosts:
        - localhost:27017
      options:

test:
  sessions:
    default:
      database: ucandidate_api_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
